BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Log] (
    [id] INT NOT NULL IDENTITY(1,1),
    [date] NVARCHAR(1000) NOT NULL,
    [entryNumber] INT NOT NULL,
    [week] NVARCHAR(1000) NOT NULL,
    [topic] NVARCHAR(1000) NOT NULL,
    [description] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Log_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [Log_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
